/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Empty Spot": "空位",
    "energy": "能量",
    "Expanded Space X": "扩展空间 X",
    "Expanded Space Y": "扩展空间 Y",
    "Faster Mergeables": "更快的可合并",
    "main tab": "主选项卡",
    "missions": "任务",
    "Achievement Gotten!": "成就达成！",
    "Better Mergeable Chance": "更好的合并几率",
    "Disable respec confirmation": "禁用重洗确认",
    "leveling": "升级",
    "Quicker Mergeable Spawn": "更快的可合并生成",
    "Respec Upgrades": "重洗升级",
    "VIP Point Chance": "VIP点数几率",
    "Automatic Merge": "自动合并",
    "Improved Mergeables": "改进的可合并",
    "VIP Point Generation": "VIP点数生成",
    "All content unlocked.": "所有内容已解锁。",
    "Bonus Automatic Merge": "奖金自动合并",
    "Bonus Faster Mergeables": "奖金更快的可合并",
    "Bonus Improved Mergeables": "奖励改进的可合并项",
    "Doubles mergent point gain.": "合并点增益加倍。",
    "If you have less than one level in Automatic Merge, you will gain a level.": "如果您在自动合并中的等级少于一级，您将获得一个等级。",
    "If you have less than three levels in Expanded Space X/Y, you will gain those levels.": "如果您在扩展空间 X/Y 中的等级少于三个，您将获得这些等级。",
    "If you have less than twenty levels in Faster Mergeables, you will gain those levels.": "如果您的 更快的可合并 等级少于二十级，您将获得这些等级。",
    "mergeables": "可合并",
    "Mergent Boost": "合并提升",
    "mergent tokens": "合并代币",
    "More Mergent Tokens": "更多合并代币",
    "tokens": "代币",
    "upgrades": "升级",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Synergism ": "协同 ",
    "Kineticism ": "动力学 ",
    "Hypotheticism ": "假说 ",
    "Unlock a new set of upgrades at level ": "解锁一组新的升级在等级 ",
    "Unlock Mergent Tokens at mergeable tier ": "解锁合并代币在可合并层 ",
    "Energy Gain": "能量增益",
    "Levels Gain": "等级增益",
    "VIP Gain": "VIP增益",
    "Active Boost": "活跃提升",
    "Upgrade Boost": "升级提升",
    "Auto Boost": "自动提升",
    "Bonus Auto Upgrade ": "奖励自动升级 ",
    "Decreasing level requirement by ": "降低等级要求 ",
    "Your best mergent tokens is ": "你最好的合并代币是 ",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\(([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^([\d\.]+) \(([\d\.]+)\%\)$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\(([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have merged (.+) times.$/, '你合并了 $1 次。'],
    [/^You have made a total of (.+) mergent tokens$/, '您总共制作了 $1 合并代币'],
    [/^You have (.+) VIP Points$/, '你有 $1 VIP点数'],
    [/^You have (.+) VIP Points.$/, '你有 $1 VIP点数。'],
    [/^You have (.+) highest mergeable tier$/, '你有 $1 最高可合并层'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^You have (.+) level tokens.$/, '你有 $1 等级代币。'],
    [/^You have (.+) levels.$/, '你有 $1 等级。'],
    [/^You gain (.+) of the idle energy gain whenever you merge.\n\t\t\t\tEach merge gives (.+) energy.$/, '每当合并时，您都会获得 $1 的放置能量增益。\n\t\t\t\t每次合并都会提供 $2 能量。'],
    [/^You have (.+)  VIP Points, giving a (.+) multiplier to energy gain.$/, '您有 $1 VIP点数，能量增益倍数为 $2。'],
    [/^Giving (.+) energy per second.$/, '给予 $1 能量每秒。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Next at (.+) highest mergeable tier$/, '下一个在 $1 最高可合并层'],
    [/^Increases auto-merge speed by (.+) for each mergent upgrade.\n\t\t\t\tAuto-merge is (.+) faster.$/, '每次合并升级自动合并速度提高 $1。\n\t\t\t\t自动合并速度提高 $2。'],
    [/^Multiplies energy gain by (.+) for each total mergent token.\n\t\t\t\tGrants (.+) energy gain.$/, '将每个总合并代币的能量增益乘以 $1。\n\t\t\t\t授予 $2 能量增益。'],
    [/^Reduces the leveling threshold by (.+) for each total mergent token.\n\t\t\t\tLeveling is (.+) faster.$/, '将每个总合并代币的升级门槛降低 $1。\n\t\t\t\t升级速度加快 $2。'],
    [/^Reduces the leveling threshold by (.+) for each merge.\n\t\t\t\tLeveling is (.+) faster.$/, '每次合并将升级门槛降低 $1。\n\t\t\t\t升级速度加快 $2。'],
    [/^Gain (.+) VIP Points every second for each total mergent token.\n\t\t\t\tGrants (.+) VIP Points per second.$/, '每个合并代币每秒获得 $1 VIP点数。\n\t\t\t\t每秒授予 $2 VIP点数。'],
    [/^Increases energy gain by (.+) for each mergent upgrade.\n\t\t\t\tYou gain (.+) energy.$/, '每次合并升级将能量增益提高 $1。\n\t\t\t\t你获得 $2 能量。'],
    [/^Increases energy gain by (.+) for each level.\n\t\t\t\tYou gain (.+) energy.$/, '每个等级能量增益增加 $1。\n\t\t\t\t你获得 $2 能量。'],
    [/^Purchase for (.+) mergent tokens$/, '购买 $1 合并代币'],
    [/^Increases VIP Point gain by (.+) for each mergent upgrade\n\t\t\t\tYou gain (.+) VIP Points.$/, '每次合并升级，VIP点数增益增加 $1\n\t\t\t\t您获得 $2 VIP点数。'],
    [/^Increases VIP Point gain by (.+) for each total mergent token.\n\t\t\t\tYou gain (.+) VIP Points.$/, '每个合并代币的 VIP点数增益增加 $1。\n\t\t\t\t您获得 $2 VIP点数。'],
    [/^Giving (.+) energy per second.$/, '每秒提供 $1 能量。'],
    [/^You gain (.+) of the idle VIP Point gain whenever you perform a merge.\n\t\t\t\tEach merge gives you (.+) VIP points.$/, '每当您执行合并时，您都会获得 $1 的放置 VIP点数 增益。\n\t\t\t\t每次合并会给您 $2 VIP点数。'],
    [/^Unlock Leveling at (.+) energy (.+)$/, '解锁升级当达到 $1 能量 $2'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^Reach a tier (.+) mergeable.$/, '达到层级 $1 可合并。'],
    [/^Reach (.+) energy.$/, '达到 $1 能量。'],
    [/^Reach (.+) normal merges.$/, '达到 $1 普通合并。'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) \/ ([\d\.,]+) VIP points$/, '$1 \/ $2 VIP点数'],
    [/^\+([\d\.,]+) VIP Point$/, '\+$1 VIP点数'],
    [/^\+([\d\.,]+) VIP Points$/, '\+$1 VIP点数'],
    [/^\+([\d\.,]+) VIP Points each second$/, '每秒 \+$1 VIP点数'],
    [/^\+([\d\.,]+) VIP Points, \+(.+) VIP Point each second$/, '\+$1 VIP点数，每秒 \+$2 VIP点数'],
    [/^\+([\d\.,]+) VIP Points, \+(.+) VIP Points each second$/, '\+$1 VIP点数，每秒 \+$2 VIP点数'],
    [/^Tier ([\d\.,]+)$/, '层 $1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) energy\n(.+)Amount: (.+)\n(.+)Mergeables spawn (.+) faster$/, '成本: $1 能量\n$2数量: $3\n$4可合并的生成速度加快 $5'],
    [/^Cost: (.+) energy\n(.+)Amount: (.+)\n(.+)Adds (.+) more columns$/, '成本: $1 能量\n$2数量: $3\n$4增加 $5 列'],
    [/^Cost: (.+) energy\n(.+)Amount: (.+)\n(.+)Adds (.+) more rows$/, '成本: $1 能量\n$2数量: $3\n$4增加 $5 行'],
    [/^Cost: (.+) energy\n(.+)Amount: (.+)\n(.+)Mergeables produce (.+) more energy.$/, '成本: $1 能量\n$2数量: $3\n$4可合并生产的能量提升 $5。'],
    [/^Cost: (.+) energy\n(.+)Amount: (.+)\n(.+)Enables Auto\-Merge \(at (.+) seconds initially\).$/, '成本: $1 能量\n$2数量: $3\n$4启用自动合并（初始间隔 $5 秒）。'],
    [/^Cost: (.+) energy\n(.+)Amount: (.+)\n(.+)Grants (.+) VIP Points per second.$/, '成本: $1 能量\n$2数量: $3\n$4每秒授予 $5 VIP点数。'],
    [/^Cost: (.+) level tokens\n(.+)Amount: (.+)\n(.+)Adds a (.+) chance to make the next mergeable spawn (.+) earlier upon merge.$/, '成本: $1 等级代币\n$2数量: $3\n$4增加 $5 的几率使下一个可合并生成在合并时提前 $6 秒。'],
    [/^Cost: (.+) level tokens\n(.+)Amount: (.+)\n(.+)Adds a (.+) chance to gain (.+) tier when merging.$/, '成本: $1 等级代币\n$2数量: $3\n$4合并时有 $5 的几率获得 $6 层级。'],
    [/^Cost: (.+) level tokens\n(.+)Amount: (.+)\n(.+)Adds a (.+) chance to get (.+) VIP Points when merging.$/, '成本: $1 等级代币\n$2数量: $3\n$4合并时有 $5 的几率获得 $6 VIP点数。'],
    [/^Cost: (.+) level tokens\n(.+)Amount: (.+)\n(.+)You always have (.+) Expanded Space X levels.$/, '成本: $1 等级代币\n$2数量: $3\n$4你总是有 $5 扩展空间 X 等级。'],
    [/^Cost: (.+) level tokens\n(.+)Amount: (.+)\n(.+)You always have (.+) Expanded Space Y levels.$/, '成本: $1 等级代币\n$2数量: $3\n$4你总是有 $5 扩展空间 Y 等级。'],
    [/^Cost: (.+) level tokens\n(.+)Amount: (.+)\n(.+)You always have (.+) Automatic Merge levels.$/, '成本: $1 等级代币\n$2数量: $3\n$4你总是有 $5 自动合并等级。'],
    [/^Cost: (.+) level tokens\n(.+)Amount: (.+)\n(.+)You always have (.+) Faster Mergeables levels.$/, '成本: $1 等级代币\n$2数量: $3\n$4你总是有 $5 更快的可合并等级。'],
    [/^Cost: (.+) level tokens\n(.+)Amount: (.+)\n(.+)You always have (.+) Improved Mergeables levels.$/, '成本: $1 等级代币\n$2数量: $3\n$4你总是有 $5 改进的可合并等级。'],
    [/^Cost: (.+) level tokens\n(.+)Amount: (.+)\n(.+)You gain (.+) more mergent tokens.$/, '成本: $1 等级代币\n$2数量: $3\n$4您获得的合并代币增加了 $5。'],
    [/^Cost: (.+) mergent tokens$/, '成本：$1 合并代币'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);